/**
 * 弈樂科技常用查詢人員名單
 */
export const PRESET_CONTACTS = [
  { name: '姚閔智', email: 'timyao@yile.com.tw' },
  { name: '蕭詠耀', email: 'yisonhsiao@yile.com.tw' },
  { name: '卓緯倫', email: 'wlcho@yile.com.tw' },
  { name: '吳家榮', email: 'stukawu@yile.com.tw' },
  { name: '邱于芳', email: 'matildaciou@yile.com.tw' },
  { name: '王巧聆', email: 'charlenewang@yile.com.tw' },
  { name: '吳怡賢', email: 'vivianwu@yile.com.tw' },
  { name: '林千筠', email: 'lauralin@yile.com.tw' },
  { name: '藍翊軒', email: 'ericlan@yile.com.tw' },
  { name: '林志澤', email: 'jetlin@yile.com.tw' },
  { name: '吳函融', email: 'hanrongwu@yile.com.tw' },
  { name: '喬貞朋', email: 'mayachiao@yile.com.tw' },
  { name: '吳梓煊', email: 'meziwu@yile.com.tw' },
  { name: '葉耀升', email: 'terryyeh@yile.com.tw' },
  { name: '王佑哲', email: 'arieswang@yile.com.tw' },
  { name: '董維誠', email: 'jasontung@yile.com.tw' },
  { name: '陳漢章', email: 'hertzchen@yile.com.tw' },
  { name: '朱哲緯', email: 'sadochu@yile.com.tw' },
  { name: '林志憲', email: 'samuellin@yile.com.tw' },
  { name: '劉浩閔', email: 'alomarliu@yile.com.tw' },
  { name: '陳思銘', email: 'joechen@yile.com.tw' },
  { name: '曾建穎', email: 'brucetseng@yile.com.tw' },
  { name: '張容溱', email: 'cherryzhang@yile.com.tw' },
  { name: '徐千雅', email: 'normashiu@yile.com.tw' },
  { name: '洪瀛華', email: 'blackteahong@yile.com.tw' },
  { name: '潘紫涵', email: 'alicepan@yile.com.tw' },
  { name: '張義宏', email: 'chuckchang@yile.com.tw' },
  { name: '莊文緯', email: 'rexchuang@yile.com.tw' },
  { name: '陳立恩', email: 'samchen@yile.com.tw' },
  { name: '黃士欣', email: 'timhuang@yile.com.tw' },
  { name: '朱泓達', email: 'jimchu@yile.com.tw' },
];
